import Head from "next/head";
import styles from "../styles/Home.module.css";
import { useSpring, animated, config } from "react-spring";
import { useHeight } from "../hooks/useHeight";
import { useState } from "react";

export default function Home() {
  const [showA, setShowA] = useState(false);
  const [showB, setShowB] = useState(false);
  const [heightRef, height] = useHeight();

  const fadeStyles = useSpring({
    from: { opacity: 0 },
    to: {
      opacity: showA ? 1 : 0,
    },
  });

  const slideInStyles = useSpring({
    config: { ...config.stiff },
    from: { opacity: 0, height: 0 },
    to: {
      opacity: showB ? 1 : 0,
      height: showB ? height : 0,
    },
  });

  return (
    <div className={styles.container}>
      <Head>
        <title>React Animation Sandbox</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1>React Animation Exampes</h1>
        <button onClick={() => setShowA((s) => !s)}>
          {showA ? "Hide" : "Show"}
        </button>
        <animated.div style={fadeStyles}>I am animated</animated.div>

        <hr />

        <button onClick={() => setShowB((s) => !s)}>
          {showB ? "Slide Up" : "Slide Down"}
        </button>
        <animated.div style={{ ...slideInStyles, overflow: "hidden" }}>
          <div ref={heightRef}>
            This content will fade in and fade out with sliding <br />
            This content will fade in and fade out with sliding <br />
            This content will fade in and fade out with sliding <br />
            This content will fade in and fade out with sliding <br />
          </div>
        </animated.div>
      </main>
    </div>
  );
}
